import type { Metadata } from "next";
import { Inter, Source_Serif_4, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const fontSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={cn("font-sans", inter.variable)}>
      <body
        className={`${inter.variable} ${fontSerif.variable} ${fontMono.variable} antialiased bg-ft-gray-900 text-ft-gray-300 bg-[url("/image.png")] bg-center md:bg-top-right`}
      >
        <main className="container max-w-7xl mx-auto s">{children}</main>
      </body>
    </html>
  );
}
